### ISSUE TITLE
Load/implement revised splash page

### ISSUE THREAD

**Issue by arouault** [MAPC/trailmap2#62] opened 2017-05-09 21:14 UTC
Please implement this splash page package 

[TrailMap_SplashPage.zip](https://github.com/MAPC/trailmap2/files/988022/TrailMap_SplashPage.zip)

**Comment by allthesignals** [comment] 2017-05-10 16:37
Duplicate of #57?

**Comment by allthesignals** [comment] 2017-05-10 17:47
There are a few issues migrating this design so far:
 - A number of unclosed HTML tags, including a `<p>` tag on line 63 and `<strong>` on line 12

Ember can't compile the html templates from Javascript unless it's valid HTML. I went ahead and fixed these issues, but for some reason, the presence of an unclosed `<strong>` tag is really important for the buttons below it, because properly closing that tag creates the following design glitch: 

![image](https://cloud.githubusercontent.com/assets/5004319/25912970/21820746-3587-11e7-8d38-6b376915427b.png)

**Closed as completed** 2017-05-17 20:36 UTC
